In [1]:
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'

In [2]:
s = pd.Series(np.arange(10))
s[3] = np.nan
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [3]:
s.count()

9

In [10]:
np.random.randint(5)

2

In [14]:
np.random.randint(10, size=5)

array([2, 9, 5, 4, 9])

In [20]:
np.random.seed(1)
np.random.randint(10, size=5)

array([5, 8, 9, 5, 0])

In [26]:
np.random.randint(10, size=5)

array([0, 1, 8, 8, 3])

In [27]:
import time
np.random.seed(int(time.time()))
np.random.randint(10, size=5)

array([7, 9, 9, 1, 9])

In [28]:
np.random.randint(10, size=(5,5))

array([[1, 3, 2, 8, 5],
       [4, 1, 9, 7, 8],
       [2, 8, 2, 4, 9],
       [2, 1, 7, 0, 3],
       [0, 6, 8, 3, 5]])

In [29]:
np.random.seed(1)
df = pd.DataFrame(np.random.randint(10, size=(5,5)))
df.iloc[2,2] = np.nan
df

0  1    2  3  4
0  5  8  9.0  5  0
1  0  1  7.0  6  9
2  2  4  NaN  2  4
3  2  4  7.0  7  9
4  1  7  0.0  6  9

In [30]:
df.count()

0    5
1    5
2    4
3    5
4    5
dtype: int64

In [31]:
df.iloc[0].value_counts()

0
5.0    2
8.0    1
9.0    1
0.0    1
Name: count, dtype: int64

In [32]:
import seaborn as sns
titanic = pd.read_csv('data/test.csv')
titanic.head(3)

Unnamed: 0  survived  pclass     sex   age  sibsp  parch     fare embarked  \
0           0         0       3    male  22.0      1      0   7.2500        S   
1           1         1       1  female  38.0      1      0  71.2833        C   
2           2         1       3  female  26.0      0      0   7.9250        S   

   class    who  adult_male deck  embark_town alive  alone  
0  Third    man        True  NaN  Southampton    no  False  
1  First  woman       False    C    Cherbourg   yes  False  
2  Third  woman       False  NaN  Southampton   yes   True

In [33]:
titanic.count()

Unnamed: 0     891
survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [34]:
titanic['survived'].value_counts(True)

survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [35]:
titanic['alive'].dtype
titanic['alive'].value_counts()
titanic['alive'].value_counts(True)

dtype('O')

alive
no     549
yes    342
Name: count, dtype: int64

alive
no     0.616162
yes    0.383838
Name: proportion, dtype: float64

In [36]:
titanic['sex'].value_counts(True)

sex
male      0.647587
female    0.352413
Name: proportion, dtype: float64

In [37]:
titanic[['sex','alive']]

sex alive
0      male    no
1    female   yes
2    female   yes
3    female   yes
4      male    no
..      ...   ...
886    male    no
887  female   yes
888  female    no
889    male   yes
890    male    no

[891 rows x 2 columns]

In [41]:
titanic[['sex','alive']].value_counts()

sex     alive
male    no       468
female  yes      233
male    yes      109
female  no        81
Name: count, dtype: int64

In [42]:
pd.DataFrame(titanic[['sex','alive']].value_counts())

count
sex    alive       
male   no       468
female yes      233
male   yes      109
female no        81

In [52]:
s = pd.Series(np.random.randint(10, size=100))
s

0     9
1     7
2     6
3     9
4     1
     ..
95    6
96    0
97    9
98    2
99    6
Length: 100, dtype: int32

In [53]:
s.value_counts()

7    17
9    14
8    11
0    10
1     9
3     9
4     9
2     9
6     8
5     4
Name: count, dtype: int64

In [57]:
s.value_counts().sort_index(ascending=True)

0    10
1     9
2     9
3     9
4     9
5     4
6     8
7    17
8    11
9    14
Name: count, dtype: int64

In [58]:
s.value_counts().sort_index(ascending=False)

9    14
8    11
7    17
6     8
5     4
4     9
3     9
2     9
1     9
0    10
Name: count, dtype: int64

In [60]:
s.value_counts().sort_values()

5     4
6     8
1     9
3     9
4     9
2     9
0    10
8    11
9    14
7    17
Name: count, dtype: int64

In [61]:
s.value_counts().sort_values(ascending=False)

7    17
9    14
8    11
0    10
1     9
3     9
4     9
2     9
6     8
5     4
Name: count, dtype: int64

In [64]:
df = pd.DataFrame(np.random.randint(10, size=(5, 5)))
df

0  1  2  3  4
0  9  3  9  1  4
1  4  6  8  8  9
2  2  7  5  5  4
3  5  8  5  8  1
4  1  8  7  0  3

In [65]:
df.sort_values(by = 1)

0  1  2  3  4
0  9  3  9  1  4
1  4  6  8  8  9
2  2  7  5  5  4
3  5  8  5  8  1
4  1  8  7  0  3

In [66]:
df.sort_values(by=0)

0  1  2  3  4
4  1  8  7  0  3
2  2  7  5  5  4
1  4  6  8  8  9
3  5  8  5  8  1
0  9  3  9  1  4

In [70]:
df = pd.DataFrame({'num_legs':[2, 4, 4, 6],
         'num_wings': [2, 0, 0, 0],},
         index=['falcon', 'dog', 'cat', 'ant'])
df

num_legs  num_wings
falcon         2          2
dog            4          0
cat            4          0
ant            6          0

In [74]:
df.sort_values(by='num_legs', ascending=False)

num_legs  num_wings
ant            6          0
dog            4          0
cat            4          0
falcon         2          2

In [75]:
np.random.seed(1)
df = pd.DataFrame(np.random.randint(10, size=(4,8)))
df

0  1  2  3  4  5  6  7
0  5  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

In [80]:
df.sum(axis=1)

0    105
1    102
2    123
3    126
dtype: int64

In [81]:
df.sum(axis=0)

0         24
1         33
2         25
3         24
4         15
5         10
6          5
7         16
total    304
dtype: int64

In [83]:
df['total']= 0
df['total']=df.sum(axis=1)
df

0  1  2  3  4  5  6  7  total
0  5  8  9  5  0  0  1  7     35
1  6  9  2  4  5  2  4  2     34
2  4  7  7  9  1  7  0  6     41
3  9  9  7  6  9  1  0  1     42

In [84]:
df.mean()

0         6.00
1         8.25
2         6.25
3         6.00
4         3.75
5         2.50
6         1.25
7         4.00
total    38.00
dtype: float64

In [85]:
df.mean(axis=1)

0    7.777778
1    7.555556
2    9.111111
3    9.333333
dtype: float64

In [86]:
df.min(axis=1)

0    0
1    2
2    0
3    0
dtype: int64

In [91]:
df.loc['max_data'] = 0
df.loc['max_data']=df.max()
df

0  1  2  3  4  5  6  7  total
0         5  8  9  5  0  0  1  7     35
1         6  9  2  4  5  2  4  2     34
2         4  7  7  9  1  7  0  6     41
3         9  9  7  6  9  1  0  1     42
max_data  9  9  9  9  9  7  4  7     42

In [92]:
df

0  1  2  3  4  5  6  7  total
0         5  8  9  5  0  0  1  7     35
1         6  9  2  4  5  2  4  2     34
2         4  7  7  9  1  7  0  6     41
3         9  9  7  6  9  1  0  1     42
max_data  9  9  9  9  9  7  4  7     42

In [96]:
df

0  1  2  3  4  5  6  7  total
0         5  8  9  5  0  0  1  7     35
1         6  9  2  4  5  2  4  2     34
2         4  7  7  9  1  7  0  6     41
3         9  9  7  6  9  1  0  1     42
max_data  9  9  9  9  9  7  4  7     42

In [99]:
df.drop(index=1)

0  1  2  3  4  5  6  7  total
0         5  8  9  5  0  0  1  7     35
2         4  7  7  9  1  7  0  6     41
3         9  9  7  6  9  1  0  1     42
max_data  9  9  9  9  9  7  4  7     42

In [108]:
df.drop(columns=3)
df

0  1  2  4  5  6  7  total
0         5  8  9  0  0  1  7     35
1         6  9  2  5  2  4  2     34
2         4  7  7  1  7  0  6     41
3         9  9  7  9  1  0  1     42
max_data  9  9  9  9  7  4  7     42

0  1  2  3  4  5  6  7  total
0         5  8  9  5  0  0  1  7     35
1         6  9  2  4  5  2  4  2     34
2         4  7  7  9  1  7  0  6     41
3         9  9  7  6  9  1  0  1     42
max_data  9  9  9  9  9  7  4  7     42

In [109]:
df.iloc[1,1] = np.nan
df

0    1  2  3  4  5  6  7  total
0         5  8.0  9  5  0  0  1  7     35
1         6  NaN  2  4  5  2  4  2     34
2         4  7.0  7  9  1  7  0  6     41
3         9  9.0  7  6  9  1  0  1     42
max_data  9  9.0  9  9  9  7  4  7     42

In [111]:
df.dropna()

0    1  2  3  4  5  6  7  total
0         5  8.0  9  5  0  0  1  7     35
2         4  7.0  7  9  1  7  0  6     41
3         9  9.0  7  6  9  1  0  1     42
max_data  9  9.0  9  9  9  7  4  7     42

In [114]:
df.dropna(axis=1)

0  2  3  4  5  6  7  total
0         5  9  5  0  0  1  7     35
1         6  2  4  5  2  4  2     34
2         4  7  9  1  7  0  6     41
3         9  7  6  9  1  0  1     42
max_data  9  9  9  9  7  4  7     42

In [116]:
df

0    1  2  3  4  5  6  7  total
0         5  8.0  9  5  0  0  1  7     35
1         6  NaN  2  4  5  2  4  2     34
2         4  7.0  7  9  1  7  0  6     41
3         9  9.0  7  6  9  1  0  1     42
max_data  9  9.0  9  9  9  7  4  7     42

In [117]:
df.dropna(inplace=True)

In [118]:
df

0    1  2  3  4  5  6  7  total
0         5  8.0  9  5  0  0  1  7     35
2         4  7.0  7  9  1  7  0  6     41
3         9  9.0  7  6  9  1  0  1     42
max_data  9  9.0  9  9  9  7  4  7     42

In [119]:
df

0    1  2  3  4  5  6  7  total
0         5  8.0  9  5  0  0  1  7     35
2         4  7.0  7  9  1  7  0  6     41
3         9  9.0  7  6  9  1  0  1     42
max_data  9  9.0  9  9  9  7  4  7     42

In [120]:
df.iloc[1,1] = np.nan

In [121]:
df

0    1  2  3  4  5  6  7  total
0         5  8.0  9  5  0  0  1  7     35
2         4  NaN  7  9  1  7  0  6     41
3         9  9.0  7  6  9  1  0  1     42
max_data  9  9.0  9  9  9  7  4  7     42

In [122]:
df.fillna(1)
df

0    1  2  3  4  5  6  7  total
0         5  8.0  9  5  0  0  1  7     35
2         4  1.0  7  9  1  7  0  6     41
3         9  9.0  7  6  9  1  0  1     42
max_data  9  9.0  9  9  9  7  4  7     42

0    1  2  3  4  5  6  7  total
0         5  8.0  9  5  0  0  1  7     35
2         4  NaN  7  9  1  7  0  6     41
3         9  9.0  7  6  9  1  0  1     42
max_data  9  9.0  9  9  9  7  4  7     42

In [123]:
df.fillna(1, inplace=True)
df

0    1  2  3  4  5  6  7  total
0         5  8.0  9  5  0  0  1  7     35
2         4  1.0  7  9  1  7  0  6     41
3         9  9.0  7  6  9  1  0  1     42
max_data  9  9.0  9  9  9  7  4  7     42

In [124]:
df.astype(int)

0  1  2  3  4  5  6  7  total
0         5  8  9  5  0  0  1  7     35
2         4  1  7  9  1  7  0  6     41
3         9  9  7  6  9  1  0  1     42
max_data  9  9  9  9  9  7  4  7     42

In [126]:
df = pd.DataFrame(np.random.randint(5, size=(5,3)))
df

0  1  2
0  2  4  0
1  3  1  2
2  0  4  1
3  2  2  1
4  0  1  3

In [127]:
df.index = [1,2,3,4,5]
df

0  1  2
1  2  4  0
2  3  1  2
3  0  4  1
4  2  2  1
5  0  1  3

In [128]:
df.columns = ['a','b','c']
df

a  b  c
1  2  4  0
2  3  1  2
3  0  4  1
4  2  2  1
5  0  1  3

In [129]:
np.sum(df['a'])

7

In [130]:
df.apply(np.sum)

a     7
b    12
c     7
dtype: int64

In [131]:
titanic

Unnamed: 0  survived  pclass     sex   age  sibsp  parch     fare  \
0             0         0       3    male  22.0      1      0   7.2500   
1             1         1       1  female  38.0      1      0  71.2833   
2             2         1       3  female  26.0      0      0   7.9250   
3             3         1       1  female  35.0      1      0  53.1000   
4             4         0       3    male  35.0      0      0   8.0500   
..          ...       ...     ...     ...   ...    ...    ...      ...   
886         886         0       2    male  27.0      0      0  13.0000   
887         887         1       1  female  19.0      0      0  30.0000   
888         888         0       3  female   NaN      1      2  23.4500   
889         889         1       1    male  26.0      0      0  30.0000   
890         890         0       3    male  32.0      0      0   7.7500   

    embarked   class    who  adult_male deck  embark_town alive  alone  
0          S   Third    man        True  NaN  Southampton    no  False  
1          C   First  woman       False    C    Cherbourg   yes  False  
2          S   Third  woman       False  NaN  Southampton   yes   True  
3          S   First  woman       False    C  Southampton   yes  False  
4          S   Third    man        True  NaN  Southampton    no   True  
..       ...     ...    ...         ...  ...          ...   ...    ...  
886        S  Second    man        True  NaN  Southampton    no   True  
887        S   First  woman       False    B  Southampton   yes   True  
888        S   Third  woman       False  NaN  Southampton    no  False  
889        C   First    man        True    C    Cherbourg   yes   True  
890        Q   Third    man        True  NaN   Queenstown    no   True  

[891 rows x 16 columns]

In [132]:
titanic[['alive','sex','class']].apply(pd.value_counts,0)

alive    sex  class
First     NaN    NaN  216.0
Second    NaN    NaN  184.0
Third     NaN    NaN  491.0
female    NaN  314.0    NaN
male      NaN  577.0    NaN
no      549.0    NaN    NaN
yes     342.0    NaN    NaN

In [133]:
df

a  b  c
1  2  4  0
2  3  1  2
3  0  4  1
4  2  2  1
5  0  1  3

In [140]:
def diff(x) :
    return x.max()-x.min()

In [142]:
df

a  b  c
1  2  4  0
2  3  1  2
3  0  4  1
4  2  2  1
5  0  1  3

In [144]:
df['b'].max()

4

In [145]:
diff(df['b'])

3

In [146]:
df.apply(diff)

a    3
b    3
c    3
dtype: int64

In [147]:
df

a  b  c
1  2  4  0
2  3  1  2
3  0  4  1
4  2  2  1
5  0  1  3

In [148]:
ages = [0,4,6,4,5,2,10,21,23,27,37,61,72,89]

In [149]:
data = ages
bins = [0,4,18,25,35,60,100]
labels = ['영유아', '미성년자', '청년', '중년', '장년', '노년']

In [150]:
len(data)

14

In [154]:
cats = pd.cut(data,bins,labels=labels)

In [155]:
cats

[NaN, '영유아', '미성년자', '영유아', '미성년자', ..., '중년', '장년', '노년', '노년', '노년']
Length: 14
Categories (6, object): ['영유아' < '미성년자' < '청년' < '중년' < '장년' < '노년']

In [156]:
cat_list = list(cats)

In [157]:
cat_list

[nan,
 '영유아',
 '미성년자',
 '영유아',
 '미성년자',
 '영유아',
 '미성년자',
 '청년',
 '청년',
 '중년',
 '장년',
 '노년',
 '노년',
 '노년']

In [158]:
test = pd.DataFrame({'나이':ages, '연령대':cat_list})
test

나이   연령대
0    0   NaN
1    4   영유아
2    6  미성년자
3    4   영유아
4    5  미성년자
5    2   영유아
6   10  미성년자
7   21    청년
8   23    청년
9   27    중년
10  37    장년
11  61    노년
12  72    노년
13  89    노년

In [159]:
test['연령대'].value_counts()

연령대
영유아     3
미성년자    3
노년      3
청년      2
중년      1
장년      1
Name: count, dtype: int64

In [160]:
cats.categories

Index(['영유아', '미성년자', '청년', '중년', '장년', '노년'], dtype='object')

In [161]:
cats

[NaN, '영유아', '미성년자', '영유아', '미성년자', ..., '중년', '장년', '노년', '노년', '노년']
Length: 14
Categories (6, object): ['영유아' < '미성년자' < '청년' < '중년' < '장년' < '노년']

In [163]:
cats.codes

array([-1,  0,  1,  0,  1,  0,  1,  2,  2,  3,  4,  5,  5,  5], dtype=int8)

In [165]:
np.random.seed(2)
data = np.random.randint(20, size=20)
data

array([ 8, 15, 13,  8, 11, 18, 11,  8,  7,  2, 17, 11, 15,  5,  7,  3,  6,
        4, 10, 11])

In [166]:
qcat = pd.qcut(data,4,labels=['Q1','Q2','Q3','Q4'])
qcat

['Q2', 'Q4', 'Q4', 'Q2', 'Q3', ..., 'Q1', 'Q1', 'Q1', 'Q3', 'Q3']
Length: 20
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [167]:
np.sort(data)

array([ 2,  3,  4,  5,  6,  7,  7,  8,  8,  8, 10, 11, 11, 11, 11, 13, 15,
       15, 17, 18])

In [168]:
pd.value_counts(qcat)

Q1    5
Q2    5
Q3    5
Q4    5
Name: count, dtype: int64

In [169]:
df = pd.DataFrame(data, columns=['관측수'])
df

관측수
0     8
1    15
2    13
3     8
4    11
5    18
6    11
7     8
8     7
9     2
10   17
11   11
12   15
13    5
14    7
15    3
16    6
17    4
18   10
19   11

In [170]:
df['범주']=qcat
df

관측수  범주
0     8  Q2
1    15  Q4
2    13  Q4
3     8  Q2
4    11  Q3
5    18  Q4
6    11  Q3
7     8  Q2
8     7  Q2
9     2  Q1
10   17  Q4
11   11  Q3
12   15  Q4
13    5  Q1
14    7  Q2
15    3  Q1
16    6  Q1
17    4  Q1
18   10  Q3
19   11  Q3

In [171]:
df = pd.DataFrame({'a':[1,3,4,3,4],
                  'b':[2,3,1,4,5],
                  'c':[1,5,2,4,4]
                  })
df

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4

In [172]:
df.set_index('a')

b  c
a      
1  2  1
3  3  5
4  1  2
3  4  4
4  5  4

In [173]:
df.reset_index()

index  a  b  c
0      0  1  2  1
1      1  3  3  5
2      2  4  1  2
3      3  3  4  4
4      4  4  5  4

In [174]:
df

a  b  c
0  1  2  1
1  3  3  5
2  4  1  2
3  3  4  4
4  4  5  4